# Generated by Django 5.2.8 on 2026-08-02 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_preferred_language_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_journey', models.CharField(choices=[('just_received_aids', 'I just received hearing aids'), ('adjusting_to_aids', 'I am adjusting to hearing aids'), ('worn_aids_for_years', 'I have worn hearing aids for years'), ('need_help_with_current_aids', 'I need help with my current aids'), ('considering_aids', 'I am considering aids')], help_text='Where user is in their hearing journey', max_length=50)),
                ('improvement_goals', models.JSONField(default=list, help_text='List of 3 hearing improvement goals selected by user')),
                ('is_completed', models.BooleanField(default=True, help_text='Whether onboarding has been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User associated with this onboarding data', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user onboarding',
                'verbose_name_plural': 'user onboardings',
            },
        ),
    ]
