# Generated by Django 5.2.8 on 2026-08-02 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useronboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_status', models.CharField(choices=[('good', 'Good'), ('okay', 'Okay'), ('struggling', 'Struggling'), ('frustrated', 'Frustrated')], help_text='How the user is hearing today', max_length=20)),
                ('checkin_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the check-in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who submitted the check-in', on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily check-in',
                'verbose_name_plural': 'daily check-ins',
                'ordering': ['-checkin_date', '-created_at'],
                'unique_together': {('user', 'checkin_date')},
            },
        ),
    ]
