# Generated by Django 5.2.8 on 2026-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dailycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or follow-up details', null=True),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='what_went_well',
            field=models.TextField(blank=True, help_text="What went well today (for 'good' hearing status)", null=True),
        ),
    ]
