# Generated by Django 5.2.8 on 2026-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dailycheckin_notes_dailycheckin_what_went_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='what_went_okay',
            field=models.TextField(blank=True, help_text="What went okay today (for 'okay' hearing status)", null=True),
        ),
    ]
