# Generated by Django 5.2.8 on 2026-08-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dailycheckin_what_went_okay'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='why_struggling',
            field=models.TextField(blank=True, help_text="Reason why user is struggling or frustrated (for 'struggling' / 'frustrated' hearing status)", null=True),
        ),
    ]
