# Generated by Django 5.2.8 on 2026-08-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_dailycheckin_why_struggling'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Tutorial title (e.g. 'Sounds are too loud')", max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier slug', max_length=255, unique=True)),
                ('category', models.CharField(default='Sound Adjustment', help_text='Category/topic of the tutorial', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed troubleshooting text / instructions')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, etc.)', null=True, upload_to='tutorials/videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (e.g. Cloudinary, S3, YouTube, Vimeo)', max_length=500, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for the video', null=True, upload_to='tutorials/thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order sequence')),
                ('is_active', models.BooleanField(default=True, help_text='Whether tutorial is active and visible in the app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'check-in tutorial',
                'verbose_name_plural': 'check-in tutorials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
