# Generated by Django 5.2.8 on 2026-08-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_checkintutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInTutorialFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_duration', models.CharField(choices=[('just_today', 'Just today'), ('a_few_days', 'A few days'), ('more_than_1_week', 'More than 1 week'), ('getting_worse', "It's getting worse")], help_text='How long the issue has been occurring', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(help_text='Tutorial this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.checkintutorial')),
                ('user', models.ForeignKey(help_text='User who submitted feedback', on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'check-in tutorial feedback',
                'verbose_name_plural': 'check-in tutorial feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
