# Generated by Django 5.2.8 on 2026-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_checkintutorialfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkintutorialfeedback',
            name='other_challenge_text',
            field=models.TextField(blank=True, help_text="User response sharing what has been most challenging for 'Other' tutorial option", null=True),
        ),
        migrations.AlterField(
            model_name='checkintutorialfeedback',
            name='issue_duration',
            field=models.CharField(blank=True, choices=[('just_today', 'Just today'), ('a_few_days', 'A few days'), ('more_than_1_week', 'More than 1 week'), ('getting_worse', "It's getting worse")], help_text='How long the issue has been occurring', max_length=50, null=True),
        ),
    ]
