# Generated by Django 5.2.8 on 2026-08-18 15:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_checkintutorialfeedback_other_challenge_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingAidWearTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of wear time entry', verbose_name='date')),
                ('hours', models.PositiveIntegerField(default=0, help_text='Number of hours worn (0-24)', verbose_name='hours')),
                ('minutes', models.PositiveIntegerField(default=0, help_text='Number of minutes worn (0-59)', verbose_name='minutes')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or environmental context', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User logging wear time', on_delete=django.db.models.deletion.CASCADE, related_name='wear_time_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'hearing aid wear time log',
                'verbose_name_plural': 'hearing aid wear time logs',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
