# Generated by Django 5.2.8 on 2026-08-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_hearingaidweartime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_wear_goal_hours',
            field=models.PositiveIntegerField(default=8, help_text='Target daily hearing aid wear time goal in hours (default: 8 hours, customizable by admin)', verbose_name='daily wear goal (hours)'),
        ),
    ]
