# Generated by Django 5.2.8 on 2026-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkintutorial',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the video in seconds'),
        ),
    ]
