# Generated by Django 5.2.8 on 2026-08-22 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_checkintutorial_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Care Team Audiologist Consultation', help_text="Appointment title or purpose (e.g. 'Hearing Aid Adjustment Consultation')", max_length=255, verbose_name='title')),
                ('specialist_name', models.CharField(default='Care Team Hearing Specialist', help_text='Name of the audiologist, clinician, or care specialist', max_length=255, verbose_name='specialist name')),
                ('appointment_date', models.DateField(help_text='Date of the appointment (YYYY-MM-DD)', verbose_name='appointment date')),
                ('appointment_time', models.TimeField(help_text='Time of the appointment (HH:MM)', verbose_name='appointment time')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Estimated duration in minutes (e.g. 30, 45, 60)', verbose_name='duration (minutes)')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the appointment', max_length=20, verbose_name='status')),
                ('meeting_link', models.URLField(blank=True, help_text='Video call or telehealth meeting link (e.g. Google Meet, Zoom)', max_length=500, null=True, verbose_name='meeting link')),
                ('location', models.CharField(blank=True, default='Online Video Consultation', help_text='Location or consultation channel', max_length=255, verbose_name='location')),
                ('notes', models.TextField(blank=True, help_text="Instructions or guidance visible to the client (e.g. 'Please wear your hearing aids for this call')", null=True, verbose_name='notes for client')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal clinician or care team notes (not shown to client)', null=True, verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin', models.ForeignKey(blank=True, help_text='The daily check-in report that prompted this appointment (e.g. struggling/frustrated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='users.dailycheckin', verbose_name='related check-in')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who scheduled the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='created by admin/specialist')),
                ('user', models.ForeignKey(help_text='Patient or client for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='patient / client')),
            ],
            options={
                'verbose_name': 'care appointment',
                'verbose_name_plural': 'care appointments',
                'ordering': ['-appointment_date', '-appointment_time', '-created_at'],
            },
        ),
    ]
