# Generated by Django 5.2.8 on 2026-08-22 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the client', max_length=255, verbose_name='client name')),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=50, verbose_name='phone number')),
                ('description', models.TextField(help_text='Description of hearing challenge or reason for requesting an appointment', verbose_name='description / reason')),
                ('preferred_date', models.DateField(blank=True, help_text='Optional preferred date for the appointment (YYYY-MM-DD)', null=True, verbose_name='preferred date')),
                ('preferred_time', models.CharField(blank=True, help_text="Optional preferred time of day (e.g. 'Morning', '2:00 PM - 4:00 PM')", max_length=100, null=True, verbose_name='preferred time')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted & Scheduled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current review status of the appointment request', max_length=20, verbose_name='status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal clinician or admin notes regarding this request', null=True, verbose_name='admin / care team notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, help_text='The scheduled appointment created by admin when accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_request', to='users.appointment', verbose_name='scheduled appointment')),
                ('user', models.ForeignKey(help_text='User requesting the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL, verbose_name='user / client')),
            ],
            options={
                'verbose_name': 'appointment request',
                'verbose_name_plural': 'appointment requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
