# Generated by Django 5.2.8 on 2026-08-23 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_seed_default_checkin_tutorials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkintutorial',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'check-in tutorial video', 'verbose_name_plural': 'check-in tutorial videos'},
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email address where admin reply will be delivered', max_length=254, verbose_name='contact email')),
                ('category', models.CharField(choices=[('sound_quality', 'Sound Quality'), ('bluetooth_syncing', 'Bluetooth & Syncing'), ('battery_charging', 'Battery & Charging'), ('hardware_fit_comfort', 'Hardware Fit & Comfort'), ('other', 'Other')], help_text='Category: Sound Quality, Bluetooth & Syncing, Battery & Charging, Hardware Fit & Comfort, Other', max_length=50, verbose_name='issue category')),
                ('description', models.TextField(help_text='Detailed description of the issue faced by the user', verbose_name='issue description')),
                ('device_model_info', models.CharField(blank=True, help_text='Optional device model or OS details (e.g. iPhone 15 / Hearing Aid Model X)', max_length=255, null=True, verbose_name='device / OS info')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved / Replied'), ('closed', 'Closed')], default='pending', help_text='Current resolution status of this issue', max_length=20, verbose_name='status')),
                ('admin_reply', models.TextField(blank=True, help_text='Care team / admin response message that will be emailed to the user', null=True, verbose_name='admin reply / email response')),
                ('is_reply_sent', models.BooleanField(default=False, help_text='Whether the admin reply has been dispatched via email to the user', verbose_name='reply email sent')),
                ('replied_at', models.DateTimeField(blank=True, help_text='Timestamp when the email reply was sent', null=True, verbose_name='replied at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, help_text='Admin user who replied to the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_issues', to=settings.AUTH_USER_MODEL, verbose_name='replied by admin')),
                ('user', models.ForeignKey(help_text='User reporting the issue', on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to=settings.AUTH_USER_MODEL, verbose_name='user / client')),
            ],
            options={
                'verbose_name': 'issue report',
                'verbose_name_plural': 'issue reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
