# Generated by Django 5.2.8 on 2026-08-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_checkintutorial_options_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkintutorialfeedback',
            name='tutorial',
            field=models.ForeignKey(blank=True, help_text='Optional tutorial this feedback belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='users.checkintutorial'),
        ),
    ]
