# Generated by Django 5.2.8 on 2026-09-22 02:53

import users.video_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_checkintutorialfeedback_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkintutorial',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom cover thumbnail image for the video (available for both file upload and YouTube/video URL)', null=True, upload_to='tutorials/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='checkintutorial',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, WebM, etc. Max: 500MB) OR enter a Video URL below.', null=True, upload_to='tutorials/videos/', validators=[users.video_utils.validate_video_file_size]),
        ),
        migrations.AlterField(
            model_name='checkintutorial',
            name='video_url',
            field=models.URLField(blank=True, help_text="External video URL or YouTube link (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...). Set YouTube video to 'Unlisted' so patients can watch without signing in.", max_length=1000, null=True),
        ),
    ]
