# Generated by Django 5.2.8 on 2026-08-24 10:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPromptSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short label e.g. 'Improve Hearing Score'", max_length=150, verbose_name='prompt title')),
                ('prompt_text', models.TextField(help_text="Full query sent to AI e.g. 'How can I improve my hearing score?'", verbose_name='prompt question text')),
                ('category', models.CharField(choices=[('hearing_score', 'Hearing Score'), ('noisy_environments', 'Noisy Environments'), ('tinnitus', 'Tinnitus Support'), ('progress', 'Progress Tracking'), ('device_care', 'Device Care & Bluetooth'), ('general', 'General')], default='general', max_length=50, verbose_name='category')),
                ('icon', models.CharField(blank=True, default='help_outline', help_text="Material icon name for UI display e.g. 'trending_up', 'volume_up', 'hearing'", max_length=50, verbose_name='material icon name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'quick prompt suggestion',
                'verbose_name_plural': 'quick prompt suggestions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='session id')),
                ('title', models.CharField(default='Hearing Improvement Assistant', help_text='Auto-generated or user-defined title for this chat topic', max_length=255, verbose_name='session title')),
                ('is_active', models.BooleanField(default=True, help_text='Active chat session flag', verbose_name='is active')),
                ('last_interaction_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last interaction at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI chat session',
                'verbose_name_plural': 'AI chat sessions',
                'ordering': ['-last_interaction_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System Context')], default='user', max_length=20, verbose_name='sender')),
                ('message_text', models.TextField(help_text='Text content of the message', verbose_name='message text')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of user hearing score, wear time, and app state when message was sent', null=True, verbose_name='user context snapshot')),
                ('model_name', models.CharField(blank=True, default='gpt-4o-mini', help_text='OpenAI model used to generate assistant response', max_length=50, verbose_name='AI model')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='tokens used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_chatbot.aichatsession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'AI chat message',
                'verbose_name_plural': 'AI chat messages',
                'ordering': ['created_at'],
            },
        ),
    ]
