# Generated by Django 5.2.8 on 2026-08-18 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Care Team Support Chat', help_text='Subject or title for this support thread', max_length=255, verbose_name='subject')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Status of the support chat', max_length=50, verbose_name='status')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the most recent message in thread', verbose_name='last message timestamp')),
                ('unread_user_count', models.PositiveIntegerField(default=0, help_text='Number of unread messages waiting for the user', verbose_name='unread count for user')),
                ('unread_admin_count', models.PositiveIntegerField(default=0, help_text='Number of unread messages waiting for care team admin', verbose_name='unread count for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, help_text='Care specialist assigned to this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='assigned admin / care specialist')),
                ('user', models.ForeignKey(help_text='User seeking support from care team', on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'support conversation',
                'verbose_name_plural': 'support conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_admin', models.BooleanField(default=False, help_text='True if sent by care team / admin, False if sent by mobile app user', verbose_name='is from admin')),
                ('sender_name', models.CharField(blank=True, help_text="Display name of the message sender e.g. 'Care Team', 'Dr. Sarah'", max_length=255, verbose_name='sender display name')),
                ('message_text', models.TextField(blank=True, help_text='Text content of the message', verbose_name='message text')),
                ('attachment', models.FileField(blank=True, help_text='Uploaded image, audio voice note, or document attachment', null=True, upload_to='support_chat/attachments/', verbose_name='file attachment')),
                ('attachment_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio Voice Note'), ('file', 'Document File')], default='text', help_text='Type of attachment: text, image, audio, or file', max_length=20, verbose_name='attachment type')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this message', verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when message was marked read', null=True, verbose_name='read timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(help_text='Parent support conversation thread', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_chat.supportconversation', verbose_name='conversation')),
                ('sender', models.ForeignKey(help_text='User or Admin who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'support message',
                'verbose_name_plural': 'support messages',
                'ordering': ['created_at'],
            },
        ),
    ]
