# Generated by Django 5.2.8 on 2026-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Uploaded picture, video, audio voice note, or document attachment', null=True, upload_to='support_chat/attachments/', verbose_name='file attachment'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='attachment_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image / Picture'), ('video', 'Video'), ('audio', 'Audio / Voice Note'), ('file', 'Document / File')], default='text', help_text='Type of attachment: text, image, video, audio, or file', max_length=20, verbose_name='attachment type'),
        ),
    ]
