# Generated by Django 5.2.8 on 2026-08-15 12:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(help_text='Week number (1 to 6)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='week number')),
                ('title', models.CharField(help_text="Tutorial title (e.g. 'Awareness', 'Adjustment')", max_length=255, verbose_name='title')),
                ('banner_text', models.TextField(help_text="Banner / summary message shown on user dashboard (e.g. 'Your brain is waking up to more sound. This is expected.')", verbose_name='banner text')),
                ('description', models.TextField(blank=True, help_text='Detailed tutorial content, guide, and instructions', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, etc.)', null=True, upload_to='weekly_tutorials/videos/', verbose_name='video file')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (e.g. YouTube, Vimeo, Cloudinary, S3)', max_length=500, null=True, verbose_name='video url')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image for the tutorial', null=True, upload_to='weekly_tutorials/thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds')),
                ('what_you_will_learn', models.JSONField(blank=True, default=list, help_text='List of key takeaways/learning points (JSON list of strings)', verbose_name='what you will learn')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tutorial is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'weekly tutorial',
                'verbose_name_plural': 'weekly tutorials',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='UserWeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_start_date', models.DateField(default=django.utils.timezone.now, help_text='Date when user started their 6-week hearing journey', verbose_name='journey start date')),
                ('completed_weeks', models.JSONField(blank=True, default=list, help_text='List of completed week numbers e.g. [1, 2]', verbose_name='completed weeks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User associated with this weekly progress', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user weekly progress',
                'verbose_name_plural': 'user weekly progress records',
            },
        ),
    ]
