# Generated by Django 5.2.8 on 2026-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EverydayListeningTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier slug e.g. 'reduce-background-noise', 'face-the-speaker'", max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(help_text="Tip title e.g. 'Reduce Background Noise'", max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline or summary', max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, help_text='Full explanation, practical steps, and listening guidance', verbose_name='description')),
                ('audio_file', models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, AAC, etc.) or external link', null=True, upload_to='skills_strategies/listening_tips/', verbose_name='audio file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image for this tip', null=True, upload_to='skills_strategies/thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the audio in seconds', verbose_name='duration in seconds')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index (1, 2, 3...)', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this listening tip is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'everyday listening tip',
                'verbose_name_plural': 'everyday listening tips',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
