# Generated by Django 5.2.8 on 2026-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the audio in seconds', verbose_name='duration in seconds'),
        ),
    ]
