# Generated by Django 5.2.8 on 2026-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_strategies', '0002_alter_everydaylisteningtip_duration_seconds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='everydaylisteningtip',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'skills & strategy audio', 'verbose_name_plural': 'skills & strategy audios'},
        ),
        migrations.AddField(
            model_name='everydaylisteningtip',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External direct audio URL or cloud stream link (used if no audio file is uploaded)', max_length=500, null=True, verbose_name='audio stream URL'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, AAC, M4A) for this strategy', null=True, upload_to='skills_strategies/listening_tips/', verbose_name='upload audio file'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='description',
            field=models.TextField(blank=True, help_text='Full explanation, practical conversational tips, and listening guidance', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the audio in seconds (e.g. 120 = 2 minutes)', verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this strategy is active and visible to mobile users', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order index (1, 2, 3, 4, 5)', verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='slug',
            field=models.SlugField(help_text="Unique identifier slug e.g. 'start-the-conversation', 'manage-group-conversations'", max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short tagline or subtitle summary', max_length=500, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Cover thumbnail image for this strategy', null=True, upload_to='skills_strategies/thumbnails/', verbose_name='thumbnail image'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='title',
            field=models.CharField(help_text="Section title e.g. 'Start the conversation', 'Improve understanding'", max_length=255, verbose_name='title'),
        ),
    ]
