# Generated by Django 5.2.8 on 2026-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_strategies', '0003_alter_everydaylisteningtip_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingConfidenceTipProxy',
            fields=[
            ],
            options={
                'verbose_name': 'building confidence audio',
                'verbose_name_plural': '3. Building Confidence (5 Audios)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('skills_strategies.everydaylisteningtip',),
        ),
        migrations.CreateModel(
            name='CommunicationStrategyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'communication strategy audio',
                'verbose_name_plural': '2. Communication Strategies (5 Audios)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('skills_strategies.everydaylisteningtip',),
        ),
        migrations.CreateModel(
            name='EverydayListeningTipProxy',
            fields=[
            ],
            options={
                'verbose_name': 'everyday listening tip audio',
                'verbose_name_plural': '1. Everyday Listening Tips (5 Audios)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('skills_strategies.everydaylisteningtip',),
        ),
        migrations.AlterModelOptions(
            name='everydaylisteningtip',
            options={'ordering': ['category', 'order', 'created_at'], 'verbose_name': 'skills & strategy audio', 'verbose_name_plural': 'skills & strategy audios'},
        ),
        migrations.AddField(
            model_name='everydaylisteningtip',
            name='category',
            field=models.CharField(choices=[('everyday_listening_tips', 'Everyday Listening Tips'), ('communication_strategies', 'Communication Strategies'), ('building_confidence', 'Building Confidence')], db_index=True, default='everyday_listening_tips', help_text='Main section category', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='description',
            field=models.TextField(blank=True, help_text='Full explanation, practical tips, and guidance', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='slug',
            field=models.SlugField(help_text="Unique identifier slug e.g. 'reduce-background-noise', 'start-the-conversation'", max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='everydaylisteningtip',
            name='title',
            field=models.CharField(help_text="Section title e.g. 'Reduce Background Noise', 'Start the conversation'", max_length=255, verbose_name='title'),
        ),
    ]
