# Generated by Django 5.2.8 on 2026-08-16 11:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Sequential day number (1, 2, 3...)', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='day number')),
                ('title', models.CharField(help_text="Lesson title (e.g. 'Day 1: Introduction to Sound Perception')", max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, help_text="Short summary or subtitle for today's lesson", max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, help_text='Detailed lesson text, instructions, and notes', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, etc.)', null=True, upload_to='learn/videos/', verbose_name='video file')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (e.g. YouTube, Vimeo, Cloudinary, S3)', max_length=500, null=True, verbose_name='video url')),
                ('audio_file', models.FileField(blank=True, help_text='Upload audio file directly (MP3, WAV, AAC, etc.)', null=True, upload_to='learn/audios/', verbose_name='audio file')),
                ('audio_url', models.URLField(blank=True, help_text='External audio URL (e.g. Cloudinary, S3, Podcast URL)', max_length=500, null=True, verbose_name='audio url')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image for the lesson', null=True, upload_to='learn/thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the media in seconds', verbose_name='duration in seconds')),
                ('key_takeaways', models.JSONField(blank=True, default=list, help_text='List of key learning points (JSON list of strings)', verbose_name='key takeaways')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this lesson is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'daily lesson',
                'verbose_name_plural': 'daily lessons',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Date when user started their daily learning journey', verbose_name='learning start date')),
                ('completed_days', models.JSONField(blank=True, default=list, help_text='List of completed day numbers e.g. [1, 2, 3]', verbose_name='completed days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User associated with this lesson progress', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user lesson progress',
                'verbose_name_plural': 'user lesson progress records',
            },
        ),
    ]
