# Generated by Django 5.2.8 on 2026-08-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylesson',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='dailylesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='dailylesson',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, AAC, etc.) or external link', null=True, upload_to='learn/audios/', verbose_name='audio file'),
        ),
        migrations.AlterField(
            model_name='dailylesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, MOV, etc.) or external link', null=True, upload_to='learn/videos/', verbose_name='video file'),
        ),
    ]
