# Generated by Django 5.2.8 on 2026-08-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_remove_dailylesson_audio_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Your Hearing Journey', help_text='Welcome video title', max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='Get started with your daily hearing improvement plan', help_text='Short tagline or subtitle', max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, default='Watch this welcome video to learn how to get the most out of your daily lessons and hearing exercises.', help_text='Welcome video description and guidance notes', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload welcome tutorial video file (MP4, MOV, etc.) or link', null=True, upload_to='learn/welcome_videos/', verbose_name='video file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image for welcome video', null=True, upload_to='learn/welcome_thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this welcome video is active and displayed to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'welcome tutorial',
                'verbose_name_plural': 'welcome tutorials',
                'ordering': ['-created_at'],
            },
        ),
    ]
