# Generated by Django 5.2.8 on 2026-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_welcometutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeamSupportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Care Team Support Guide', help_text='Video title', max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='Connect with your dedicated hearing care specialists', help_text='Short tagline or subtitle', max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, default='Watch this video to learn how our expert care team supports your hearing progress and answers your questions.', help_text='Video description and guidance notes', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload care team support video file (MP4, MOV, etc.) or link', null=True, upload_to='learn/care_team_videos/', verbose_name='video file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image', null=True, upload_to='learn/care_team_thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is active and displayed to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'care team support video',
                'verbose_name_plural': 'care team support videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInOverviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Daily Check-in Overview', help_text='Video title', max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='Learn how tracking your hearing daily helps your progress', help_text='Short tagline or subtitle', max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, default='Watch this video to understand how daily check-ins record your hearing status and personalize your journey.', help_text='Video description and guidance notes', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload check-in overview video file (MP4, MOV, etc.) or link', null=True, upload_to='learn/checkin_overview_videos/', verbose_name='video file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image', null=True, upload_to='learn/checkin_overview_thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is active and displayed to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'check-in overview video',
                'verbose_name_plural': 'check-in overview videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
