# Generated by Django 5.2.8 on 2026-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_careteamsupportvideo_checkinoverviewvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressOverviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Progress Tracking Overview', help_text='Video title', max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='Learn how your hearing progress and improvements are measured over time', help_text='Short tagline or subtitle', max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, default='Watch this video to understand how your overall progress, streaks, and milestones are tracked.', help_text='Video description and guidance notes', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload progress overview video file (MP4, MOV, etc.) or link', null=True, upload_to='learn/progress_overview_videos/', verbose_name='video file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image', null=True, upload_to='learn/progress_overview_thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is active and displayed to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'progress overview video',
                'verbose_name_plural': 'progress overview videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
