# Generated by Django 5.2.8 on 2026-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_progressoverviewvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careteamsupportvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='checkinoverviewvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='dailylesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the media in seconds', verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='progressoverviewvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='welcometutorial',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds'),
        ),
    ]
