# Generated by Django 5.2.8 on 2026-09-22 02:53

import users.video_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_alter_careteamsupportvideo_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careteamsupportvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text="External video URL or YouTube link (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...). Set YouTube video to 'Unlisted' so patients can watch without signing in.", max_length=1000, null=True, verbose_name='video URL / YouTube link'),
        ),
        migrations.AddField(
            model_name='checkinoverviewvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text="External video URL or YouTube link (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...). Set YouTube video to 'Unlisted' so patients can watch without signing in.", max_length=1000, null=True, verbose_name='video URL / YouTube link'),
        ),
        migrations.AddField(
            model_name='dailylesson',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External audio stream URL (MP3, AAC, podcast link, etc.)', max_length=1000, null=True, verbose_name='audio URL / stream link'),
        ),
        migrations.AddField(
            model_name='dailylesson',
            name='video_url',
            field=models.URLField(blank=True, help_text="External video URL or YouTube link (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...). Set YouTube video to 'Unlisted' so patients can watch without signing in.", max_length=1000, null=True, verbose_name='video URL / YouTube link'),
        ),
        migrations.AddField(
            model_name='progressoverviewvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text="External video URL or YouTube link (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...). Set YouTube video to 'Unlisted' so patients can watch without signing in.", max_length=1000, null=True, verbose_name='video URL / YouTube link'),
        ),
        migrations.AddField(
            model_name='welcometutorial',
            name='video_url',
            field=models.URLField(blank=True, help_text="External video URL or YouTube link (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...). Set YouTube video to 'Unlisted' so patients can watch without signing in.", max_length=1000, null=True, verbose_name='video URL / YouTube link'),
        ),
        migrations.AlterField(
            model_name='careteamsupportvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom cover thumbnail image (available for both file upload and YouTube/video URL)', null=True, upload_to='learn/care_team_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='careteamsupportvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload care team support video file directly (MP4, MOV, WebM, etc. Max: 500MB) OR enter a Video URL below.', null=True, upload_to='learn/care_team_videos/', validators=[users.video_utils.validate_video_file_size], verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='checkinoverviewvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom cover thumbnail image (available for both file upload and YouTube/video URL)', null=True, upload_to='learn/checkin_overview_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='checkinoverviewvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload check-in overview video file directly (MP4, MOV, WebM, etc. Max: 500MB) OR enter a Video URL below.', null=True, upload_to='learn/checkin_overview_videos/', validators=[users.video_utils.validate_video_file_size], verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='dailylesson',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file directly (MP3, WAV, AAC, etc. Max: 100MB) OR enter an Audio URL below.', null=True, upload_to='learn/audios/', validators=[users.video_utils.validate_audio_file_size], verbose_name='audio file'),
        ),
        migrations.AlterField(
            model_name='dailylesson',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom cover thumbnail image for the lesson (available for both file upload and YouTube/video URL)', null=True, upload_to='learn/thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='dailylesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, WebM, etc. Max: 500MB) OR enter a Video URL below.', null=True, upload_to='learn/videos/', validators=[users.video_utils.validate_video_file_size], verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='progressoverviewvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom cover thumbnail image (available for both file upload and YouTube/video URL)', null=True, upload_to='learn/progress_overview_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='progressoverviewvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload progress overview video file directly (MP4, MOV, WebM, etc. Max: 500MB) OR enter a Video URL below.', null=True, upload_to='learn/progress_overview_videos/', validators=[users.video_utils.validate_video_file_size], verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='welcometutorial',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom cover thumbnail image for welcome video (available for both file upload and YouTube/video URL)', null=True, upload_to='learn/welcome_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='welcometutorial',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload welcome tutorial video file directly (MP4, MOV, WebM, etc. Max: 500MB) OR enter a Video URL below.', null=True, upload_to='learn/welcome_videos/', validators=[users.video_utils.validate_video_file_size], verbose_name='video file'),
        ),
    ]
