# Generated by Django 5.2.8 on 2026-08-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCareSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('cleaning_guide', 'Cleaning Guide'), ('care_tips', 'Care Tips'), ('troubleshooting', 'Troubleshooting'), ('user_manual', 'User Manual')], help_text='Select section type: Cleaning Guide, Care Tips, Troubleshooting, or User Manual', max_length=50, verbose_name='section type')),
                ('title', models.CharField(help_text="Section title e.g. 'Daily Cleaning Tutorial'", max_length=255, verbose_name='section title')),
                ('subtitle', models.CharField(blank=True, help_text='Short summary or subtitle', max_length=500, verbose_name='subtitle')),
                ('content_text', models.TextField(blank=True, help_text='Detailed text instructions, step-by-step cleaning guides, or troubleshooting fixes', verbose_name='text content / instructions')),
                ('manual_url', models.URLField(blank=True, help_text='Live link to online user manual (used for User Manual section)', max_length=1000, verbose_name='manual URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index (0, 1, 2...)', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'device care section',
                'verbose_name_plural': 'device care sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HearingAidBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name (e.g. Phonak, Oticon)', max_length=255, verbose_name='brand name')),
                ('slug', models.SlugField(help_text="Unique identifier slug e.g. 'phonak', 'oticon'", max_length=100, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, help_text='Brand logo or cover image', null=True, upload_to='device_care/brands/', verbose_name='brand logo / image')),
                ('description', models.TextField(blank=True, help_text='Short description of the brand', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index (0, 1, 2...)', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this brand is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hearing aid brand',
                'verbose_name_plural': 'hearing aid brands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCareVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Video title e.g. 'How to replace wax guard filter'", max_length=255, verbose_name='video title')),
                ('description', models.TextField(blank=True, help_text='Short video notes or step description', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (MP4, MOV, etc.) or external link', null=True, upload_to='device_care/videos/', verbose_name='video file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image for the video', null=True, upload_to='device_care/video_thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index (0, 1, 2...)', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='Parent care section', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='device_care.devicecaresection', verbose_name='care section')),
            ],
            options={
                'verbose_name': 'device care video',
                'verbose_name_plural': 'device care videos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HearingAidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model name (e.g. Audéo Lumity, More 1)', max_length=255, verbose_name='model name')),
                ('slug', models.SlugField(help_text="Unique identifier slug e.g. 'audeo-lumity'", max_length=100, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, help_text='Picture of the hearing aid device model', null=True, upload_to='device_care/models/', verbose_name='model picture')),
                ('description', models.TextField(blank=True, help_text='Description of the device model features', verbose_name='description')),
                ('user_manual_url', models.URLField(blank=True, help_text='Live web/PDF link to online user manual for this model', max_length=1000, verbose_name='user manual live URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index (0, 1, 2...)', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Parent hearing aid brand', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='device_care.hearingaidbrand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'hearing aid model',
                'verbose_name_plural': 'hearing aid models',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='devicecaresection',
            name='model',
            field=models.ForeignKey(help_text='Parent hearing aid model', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='device_care.hearingaidmodel', verbose_name='device model'),
        ),
    ]
