# Generated by Django 5.2.8 on 2026-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatNormalAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Audio track title (e.g. 'Acoustic Acclimation Audio Guide')", max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline or subtitle', max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, help_text='Full description, listening instructions, and notes', verbose_name='description')),
                ('audio_file', models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, AAC, etc.) or external link', null=True, upload_to='what_normal/audios/', verbose_name='audio file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image for audio track', null=True, upload_to='what_normal/audio_thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the audio in seconds', verbose_name='duration in seconds')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index (0, 1, 2...)', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this audio is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "what's normal audio",
                'verbose_name_plural': "what's normal audios",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatNormalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Video title (e.g. 'Understanding Loud Environmental Sounds')", max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline or subtitle', max_length=500, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, help_text='Full description, key points, and explanatory text', verbose_name='description')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (MP4, MOV, etc.) or external link', null=True, upload_to='what_normal/videos/', verbose_name='video file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover thumbnail image', null=True, upload_to='what_normal/thumbnails/', verbose_name='thumbnail')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index (0, 1, 2...)', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is active and visible to users', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "what's normal video",
                'verbose_name_plural': "what's normal videos",
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
