# Generated by Django 5.2.8 on 2026-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_normal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatnormalaudio',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the audio in seconds', verbose_name='duration in seconds'),
        ),
        migrations.AlterField(
            model_name='whatnormalvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Duration of the video in seconds', verbose_name='duration in seconds'),
        ),
    ]
